# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDCYZZQ0tZqoQfQT1JjYXoRtMkK4OVIM

# Limpeza
"""

import pandas as pd

# Carregar o dataset
df = pd.read_csv("game_dataset.csv")

# Dimensões do dataframe
print("Dimensões do dataset:")
print(df.shape)

# Tipos de dados
print("\nTipos de dados:")
print(df.dtypes)

# Informações gerais
print("\nInformações gerais:")
print(df.info())

# Valores ausentes
print("\nValores ausentes por coluna:")
print(df.isnull().sum())

# Quantidade de linhas duplicadas
duplicadas = df.duplicated().sum()

print("\nQuantidade de linhas duplicadas:")
print(duplicadas)



print("\nColunas do dataset:")
print(df.columns)

# Removendo coluna que não possui relevância preditiva
# (apenas identificador único)

df = df.drop(columns=["Nome do Jogo"])

print("\nColunas após remoção:")
print(df.columns)

# Tamanho antes
print("\nTamanho antes da remoção:")
print(df.shape)

# Remover linhas duplicadas
df = df.drop_duplicates()

# Tamanho depois
print("\nTamanho após remoção:")
print(df.shape)

# Conferência final
print("\nDataset final:")
print(df.head())

"""# Preenchimento de valores ausentes"""

import matplotlib.pyplot as plt



df = pd.read_csv("game_dataset.csv")

# Remover coluna sem relevância
df = df.drop(columns=["Nome do Jogo"])

# Remover duplicatas
df = df.drop_duplicates()




colunas_numericas = df.select_dtypes(include=["int64", "float64"]).columns

print("Colunas numéricas:")
print(colunas_numericas)


for coluna in colunas_numericas:

    plt.figure(figsize=(6,4))

    plt.boxplot(df[coluna].dropna())

    plt.title(f"Boxplot antes - {coluna}")

    plt.ylabel(coluna)

    plt.show()



df_tratado = df.copy()

for coluna in colunas_numericas:

    # Quartis
    Q1 = df_tratado[coluna].quantile(0.25)
    Q3 = df_tratado[coluna].quantile(0.75)

    # Intervalo interquartil
    IQR = Q3 - Q1

    # Limites
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR

    # Filtrar dados sem outliers
    df_tratado = df_tratado[
        (df_tratado[coluna] >= limite_inferior) &
        (df_tratado[coluna] <= limite_superior)
    ]


for coluna in colunas_numericas:

    plt.figure(figsize=(6,4))

    plt.boxplot(df_tratado[coluna].dropna())

    plt.title(f"Boxplot depois - {coluna}")

    plt.ylabel(coluna)

    plt.show()

# =========================
# TAMANHO FINAL
# =========================

print("\nTamanho original:")
print(df.shape)

print("\nTamanho após remoção de outliers:")
print(df_tratado.shape)

"""# Transformação de variáveis categóricas


"""

import pandas as pd

# =========================
# CARREGAR DATASET
# =========================

df = pd.read_csv("game_dataset.csv")

# =========================
# VERIFICAR VALORES AUSENTES
# =========================

print("Valores ausentes antes do tratamento:\n")

print(df[["Classificação de Usuários", "Idade Recomendada"]].isnull().sum())

# =========================
# TRATAMENTO DA COLUNA
# CLASSIFICAÇÃO DE USUÁRIOS
# =========================

# Escolha:
# Utilizar a MÉDIA, pois é uma variável contínua
# e normalmente representa notas com distribuição numérica.

media_classificacao = df["Classificação de Usuários"].mean()

df["Classificação de Usuários"] = df["Classificação de Usuários"].fillna(media_classificacao)

print("\nMédia utilizada em 'Classificação de Usuários':")
print(media_classificacao)

# =========================
# TRATAMENTO DA COLUNA
# IDADE RECOMENDADA
# =========================

# Escolha:
# Utilizar a MEDIANA, pois a coluna pode possuir
# valores extremos e a mediana sofre menos influência
# de outliers.

mediana_idade = df["Idade Recomendada"].median()

df["Idade Recomendada"] = df["Idade Recomendada"].fillna(mediana_idade)

print("\nMediana utilizada em 'Idade Recomendada':")
print(mediana_idade)

# =========================
# VERIFICAÇÃO FINAL
# =========================

print("\nValores ausentes após tratamento:\n")

print(df[["Classificação de Usuários", "Idade Recomendada"]].isnull().sum())

# =========================
# VISUALIZAÇÃO FINAL
# =========================

print("\nPrimeiras linhas do dataset tratado:\n")

print(df.head())

"""# Divisão entre treino e teste"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# =========================
# CARREGAR DATASET
# =========================

df = pd.read_csv("game_dataset.csv")

# =========================
# REMOVER COLUNA IRRELEVANTE
# =========================

df = df.drop(columns=["Nome do Jogo"])

# =========================
# IDENTIFICAR COLUNAS CATEGÓRICAS
# =========================

colunas_categoricas = df.select_dtypes(include=["object"]).columns

print("Colunas categóricas:\n")
print(colunas_categoricas)

# =========================
# LABEL ENCODING
# =========================

# O Label Encoding é utilizado em variáveis binárias,
# pois existem apenas duas categorias.
# Assim, cada categoria pode ser representada
# por 0 e 1 sem criar colunas extras.

label = LabelEncoder()

for coluna in colunas_categoricas:

    quantidade_categorias = df[coluna].nunique()

    if quantidade_categorias == 2:

        df[coluna] = label.fit_transform(df[coluna])

        print(f"\nLabel Encoding aplicado na coluna: {coluna}")

# =========================
# ONE-HOT ENCODING
# =========================

# O One-Hot Encoding é utilizado em variáveis
# com mais de duas categorias.
# Isso evita que o modelo interprete uma ordem
# numérica inexistente entre categorias.

colunas_onehot = []

for coluna in colunas_categoricas:

    if df[coluna].nunique() > 2:

        colunas_onehot.append(coluna)

# Aplicando One-Hot Encoding

df = pd.get_dummies(df, columns=colunas_onehot)

# =========================
# RESULTADO FINAL
# =========================

print("\nDataset após conversão:\n")

print(df.head())

print("\nNovas dimensões do dataframe:\n")

print(df.shape)

print("\nTipos de dados finais:\n")

print(df.dtypes)

"""# Normalização de dados

# Desafio
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.preprocessing import LabelEncoder

# Carregar dataset
df = pd.read_csv("game_dataset.csv")

# Remover coluna irrelevante
df = df.drop(columns=["Nome do Jogo"])

# Separar target
y = df["Preço"]
X = df.drop(columns=["Preço"])

# Identificar colunas categóricas
colunas_categoricas = X.select_dtypes(include=["object"]).columns

# Label Encoding para variáveis binárias
label = LabelEncoder()
for coluna in colunas_categoricas:
    if X[coluna].nunique() == 2:
        X[coluna] = label.fit_transform(X[coluna])

# One-Hot Encoding para variáveis com mais de duas categorias
X = pd.get_dummies(X, columns=[col for col in colunas_categoricas if X[col].nunique() > 2])

# Divisão treino/teste
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)

# Modelo escolhido: Random Forest
modelo = RandomForestRegressor(n_estimators=100, random_state=42)
modelo.fit(X_treino, y_treino)

# Previsões
y_pred = modelo.predict(X_teste)

# Avaliação
mae = mean_absolute_error(y_teste, y_pred)
r2 = r2_score(y_teste, y_pred)

print("Erro Absoluto Médio (MAE):", mae)
print("R²:", r2)