# -*- coding: utf-8 -*-
"""ex002.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_W2iLcsQ8kH_IIbsfZ5I91g8SgW5bHc
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

"""# Filtros a Classificador"""

# -*- coding: utf-8 -*-
# Diabetes Data Cleaning and Modeling Notebook

# =========================
# IMPORTS
# =========================
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# =========================
# CARREGAR DATASET
# =========================
df = pd.read_csv("diabetes.csv")

# =========================
# INSPEÇÃO INICIAL
# =========================
print("Dimensões do dataset:", df.shape)
print("\nTipos de dados:\n", df.dtypes)
print("\nValores ausentes por coluna:\n", df.isnull().sum())
print("\nLinhas duplicadas:", df.duplicated().sum())

# =========================
# REMOVER DUPLICATAS
# =========================
df = df.drop_duplicates()
print("\nDimensões após remoção de duplicatas:", df.shape)

# =========================
# TRATAMENTO DE OUTLIERS
# =========================
colunas_numericas = df.select_dtypes(include=["int64", "float64"]).columns

df_tratado = df.copy()
for coluna in colunas_numericas:
    Q1 = df_tratado[coluna].quantile(0.25)
    Q3 = df_tratado[coluna].quantile(0.75)
    IQR = Q3 - Q1
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR
    df_tratado = df_tratado[
        (df_tratado[coluna] >= limite_inferior) &
        (df_tratado[coluna] <= limite_superior)
    ]

print("\nTamanho original:", df.shape)
print("Tamanho após remoção de outliers:", df_tratado.shape)

# =========================
# TRATAMENTO DE VALORES AUSENTES
# =========================
# Substituir valores 0 por mediana em colunas clínicas
colunas_com_zero = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

for coluna in colunas_com_zero:
    mediana = df_tratado[coluna].median()
    df_tratado[coluna] = df_tratado[coluna].replace(0, mediana)
    print(f"Mediana utilizada em {coluna}: {mediana}")

print("\nValores ausentes após tratamento:\n", df_tratado.isnull().sum())

# =========================
# TRANSFORMAÇÃO DE VARIÁVEIS CATEGÓRICAS
# =========================
label = LabelEncoder()
df_tratado["Outcome"] = label.fit_transform(df_tratado["Outcome"])

# =========================
# DIVISÃO TREINO/TESTE
# =========================
X = df_tratado.drop(columns=["Outcome"])
y = df_tratado["Outcome"]

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)

# =========================
# MODELO DE CLASSIFICAÇÃO
# =========================
modelo = RandomForestClassifier(n_estimators=100, random_state=42)
modelo.fit(X_treino, y_treino)

# Previsões
y_pred = modelo.predict(X_teste)

# Avaliação
print("\nAcurácia:", accuracy_score(y_teste, y_pred))
print(f"Acurácia em porcentagem: {acuracia * 100:.2f}%")